### ISSUE TITLE
State file topic configs

### ISSUE THREAD

**Issue by alex036** [devshawn/kafka-gitops#41]
Hi there,

I've added some topic configs to my state file, and when running a plan, it's trying to add the configs that already exist?

Context:
Topic is pre-existing and was created using the `ccloud` cli tool. Some configs were passed at the time of topic creation using `--config`. I'm looking to 'import' the topic into the state file.

Examples:

State.yaml
```
topics:
  test_partitions:
    partitions: 128
    replication: 3
    configs:
      cleanup.policy: delete
      retention.ms: 604800000
```

ccloud kafka topic describe (removed a bunch of output)
```
Configuration

                   Name                   |        Value
+-----------------------------------------+---------------------+
  cleanup.policy                          | delete
  compression.type                        | producer
  retention.ms                            |           604800000
...
```

Plan:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update

The following actions will be performed:

Topics: 0 to create, 1 to update, 0 to delete.

~ [TOPIC] test_partitions
	~ configs:
		+ cleanup.policy: delete
		+ retention.ms: 604800000

ACLs: 0 to create, 0 to update, 0 to delete.

Plan: 0 to create, 1 to update, 0 to delete.
```

My assumption (expected outcome) was that the plan would say `There are no necessary changes; the actual state matches the desired state.` and not need to modify anything.
If I remove the additional configs from the state file, it comes back as no necessary changes. Since we created these topics with specific configs, I'd like to have the state file show those configs.

Thanks

**Comment by devshawn** [comment]
Hi @alex036, these are not showing as changes because they are considered broker defaults -- Confluent Cloud defaults to a cleanup.policy of `delete` and a retention time of `7` days, e.g. `604800000` ms.

So, when the tool looks for topic configs, it only looks for user-defined ones. Thus, the tool believes these configs have not been changed and ignores them. If you want to have the defaults explicitly defined as you have shown in your state file, you can just run an apply with the plan and it will put them in as a custom config. Confluent Cloud must not set custom configs if default values are provided. (I would do this with a test topic first to ensure nothing actually changes). 

I tested out this scenario against a Confluent Cloud cluster and saw the same.

**Comment by alex036** [comment]
Hey @devshawn,
Appreciate the prompt reply. 

I've been playing around with adding in other existing topics and I think I based most of my testing off of some test/unused topics that may have indeed been 100% default.

The other topics now have plans with the following as an example:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update

The following actions will be performed:

Topics: 0 to create, 1 to update, 0 to delete.

~ [TOPIC] accounts_receivable
	~ configs:
		- cleanup.policy
		- min.insync.replicas
		- retention.ms
		- segment.ms


ACLs: 0 to create, 0 to update, 0 to delete.

Plan: 0 to create, 1 to update, 0 to delete.
```

Then I've just been adding in those custom configs to the state and re-planning to confirm the state and the cluster are the same state.

Thanks!
